config/routes.rb
Rails.application.routes.draw do

   root 'welcome#name'
   get '/table' => 'welcome#table'
   get '/ajax' => 'welcome#ajax'
   get '/loops' => 'welcome#loops'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :cors_preflight_check
   after_filter :cors_set_access_control_headers

 # For all responses in this controller, return the CORS access control headers.

 def cors_set_access_control_headers
   headers['Access-Control-Allow-Origin'] = '*'
   headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
   headers['Access-Control-Allow-Headers'] = '*'
   headers['Access-Control-Max-Age'] = "1728000"
 end

 # If this is a preflight OPTIONS request, then short-circuit the
 # request, return only the necessary headers and return an empty
 # text/plain.

 def cors_preflight_check
   if request.method == :options
     headers['Access-Control-Allow-Origin'] = '*'
     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
     headers['Access-Control-Allow-Headers'] = '*'
     headers['Access-Control-Max-Age'] = '1728000'
     render :text => '', :content_type => 'text/plain'
   end
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def table
  end

  def name
  end

  def ajax
  end

  def loops
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsFun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/ajax.html.erb
<a href="#" onclick="checkProfanity('bunnies')">Check if word is profane</a>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Welcome!</h1>
</div>
<div class="col-md-8 col-md-offset-1">
  <table border="1"cellpadding="3" cellspacing="3" class="table" id="myTable">
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
</table>

</div>

<script type="text/javascript" charset="utf-8">
  $(function(){
    alert("Hello there!");
  });
</script>

app/views/welcome/loops.html.erb
<div class="hotpink" style="background-color: hotpink"></div>
<div class="red" style="background-color: red"></div>
<div class="blue" style="background-color: blue"></div>
<div class="green" style="background-color: green"></div>
<%= javascript_tag "switchCase()" %>

<%= link_to "Go to ajax", ajax_path, class: "go-to-btn ajax col-md-1 col-md-offset-4" %>

app/views/welcome/name.html.erb
<div class="page-header">
  <h1>Welcome!</h1>
</div>

<p>
  Here we have an input field
</p>

<%= form_tag("", method: "get", class: "name") do %>
    <%= label_tag(:first_name, "First Name:") %>
    <%= text_field_tag(:first_name) %>
  <%= submit_tag("Enter Name", class: "submit-button") %>
<% end %>
<div class="row">
  <%= link_to "Go to table", table_path, class: "go-to-btn table col-md-1 col-md-offset-4" %>
</div>

<%= javascript_tag "sayHello();" %>

app/views/welcome/table.html.erb
<div class="page-header">
  <h1>Welcome!</h1>
</div>
<p>
  Here we have a table
</p>
<div class="col-md-8 col-md-offset-2">
  <table border="1"cellpadding="3" cellspacing="3" class="table" id="myTable">
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
	<tr>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
		<td>Table Cell</td>
	</tr>
</table>

</div>

<div class="row">
  <%= link_to "Go to loops", loops_path, class: "go-to-btn ajax col-md-3 col-md-offset-4" %>
</div>

<%= javascript_tag "makeMiddlePink()" %>